data = [
    { name: "TITA", numbers: [100] },
    { name: "PAINHO", numbers: [16,17,29,30] },
    { name: "TIO LULA", numbers: [57] },
    { name: "TIO DINHO", numbers: [50] },
    { name: "JUSSARA", numbers: [12] },
    { name: "RAFINHA", numbers: [23, 84] },
    { name: "JOSY", numbers: [31] },
    { name: "KEILA", numbers: [37] },
    { name: "BIA", numbers: [26] },
    { name: "ERIKA", numbers: [11, 28, 69] },
    { name: "MAINHA", numbers: [1, 5, 43, 44,60] },
    { name: "ALBANIR", numbers: [2,9] },
    { name: "EUGENIA", numbers: [3, 8] },
    { name: "DEL", numbers: [15, 20] },
    { name: "ETIENE", numbers: [14, 18] },
    { name: "ANA MARIA", numbers: [27, 42] },
    { name: "MARIA HELENA", numbers: [40, 46] },
    { name: "AMANDA", numbers: [96] },
    { name: "HAKILA ", numbers: [7] },
    { name: "CAROL", numbers: [10] },
    { name: "LOURDES ", numbers: [33] },
    { name: "CLEOZILDA ", numbers: [34] },
    { name: "GILMA ", numbers: [19] },
    { name: "LUANA", numbers: [13] },
    { name: "CRIS SUPERVISORA", numbers: [97] },
    { name: "CARLA HC ", numbers: [6] },
    { name: "ELISA", numbers: [4] },
    { name: "ELIANE", numbers: [87] },
    { name: "DANI", numbers: [74] },
    { name: "renata ", numbers: [55] },
    { name: "GEDIELMA", numbers: [38,111] },
    { name: "MICHELINE ", numbers: [78] },
    { name: "DIANA", numbers: [36] },
    { name: "AILANA", numbers: [99] },
    { name: "LANA", numbers: [35] },
    { name: "GELY", numbers: [32,58] },
    { name: "JO", numbers: [25] },
    { name: "MARI", numbers: [21] },
    { name: "TEREZA (HC)", numbers: [52] },
    { name: "ELENI", numbers: [22] },
    { name: "ROSA", numbers: [68] },
    { name: "CARLA PRIMA", numbers: [24,66] },
    { name: "DR RENATA", numbers: [105] },
    { name: "DRA LUCIANA", numbers: [125] },
    { name: "DANI", numbers: [102] },
    { name: "DR CARNEIRO", numbers: [106,107] },
    { name: "HAIANE", numbers: [140] },
    { name: "BRIANA", numbers: [121] },
    { name: "MARISTER", numbers: [76] },
    { name: "DINA", numbers: [39] },
    { name: "LUANA", numbers: [45] },
    { name: "AMANDA", numbers: [49] },
    { name: "DAY ", numbers: [98] },
    { name: "JANEIDE", numbers: [63] },
    { name: "ELIZANDRA", numbers: [47] },
    { name: "MICHELE", numbers: [86] },
    { name: "LUCIARA", numbers: [72] },
    { name: "NAYARA", numbers: [88] },
    { name: "BARBARA", numbers: [91] },
    { name: "RAIRA", numbers: [48] },
    { name: "WAL", numbers: [54] },
    { name: "MANU", numbers: [61] },
    { name: "PATRICIA", numbers: [62] },
    { name: "FABIANA", numbers: [77] },
    { name: "SHARO", numbers: [95] },
    { name: "TANDINHA", numbers: [75] },
    { name: "FRANCISCA", numbers: [92] },
    { name: "LUCIANA DIAS", numbers: [85] },
    { name: "BETH", numbers: [90] },
    { name: "GISELI", numbers: [51] },
    { name: "MARTA ", numbers: [64] },
    { name: "CLAUDINHA", numbers: [56] },
    { name: "BERE", numbers: [71] },
    { name: "ALEX", numbers: [79] },
    { name: "JU DIAS", numbers: [53] },
    { name: "REJANE", numbers: [73] },
    { name: "ANDREA ", numbers: [59] },
    { name: "LENIRA", numbers: [80] },
    { name: "MARCIONE", numbers: [81] },
    { name: "VITORIA", numbers: [70] },
    { name: "ALEX", numbers: [83] },
    { name: "GIL ", numbers: [94] },
    { name: "ANDREZA", numbers: [89] },
    { name: "JANE SILVA", numbers: [67] },
    { name: "CRISTINA", numbers: [93] },
    { name: "LUZIANA", numbers: [139] },
    { name: "NELI", numbers: [126] },
    { name: "ROSE", numbers: [101] },
    { name: "FERNANDA", numbers: [120] },
    { name: "ADRIANA", numbers: [104] },
    { name: "KAROLINE", numbers: [135] },
    { name: "EDEZIA", numbers: [122] },
    { name: "ROSELI", numbers: [131] },
    { name: "JULIANAN", numbers: [108] },
    { name: "TEREZINHA", numbers: [138] },
    { name: "RAYANA", numbers: [103, 124 ,110] },
    { name: "FLAVIA", numbers: [133] },
    { name: "DONA DETE", numbers: [114] },
    { name: "DRA KARINA", numbers: [117] },
    { name: "ROSALIA", numbers: [130] },
    { name: "TIA FLAVIA", numbers: [119, 2, 132] },
    { name: "TIO CADITA", numbers: [113,128] },
    { name: "ALEXANDRE", numbers: [136] },
    { name: "CRIS HC", numbers: [137] },
    { name: "CAROL MÉDICA", numbers: [127] },
    { name: "PLAY", numbers: [109] },
    { name: "ADEILDA", numbers: [65] },
    { name: "MARIA CME ", numbers: [115] },
    { name: "REBECA", numbers: [123] },
    { name: "PRISCILA ", numbers: [112] },
    { name: "FABIOLA", numbers: [129] },
    { name: "PRI UPE", numbers: [82] },
    { name: "ANA LUCIA", numbers: [116,134] },
    { name: "ANA SEPHORA", numbers: [118] },
    { name: "ROBERTA HC", numbers: [141] },
    { name: "CEÇA HUOC", numbers: [142] },
];


function getRandom(min, max) {
    return Math.floor(Math.random() * (max - min + 1) + min);
}

function setRandom() {
    let number = getRandom(1, 142);
    let content = "";
    data.forEach(item => {
        if(item.numbers.includes(number)){
            content = `(${number}) ${item.name}`.toUpperCase();
            document.getElementById("content").innerHTML = content;
        }
    });
}